name: home

on: 
  pull_request:
  push:
    branches:
      - main
    paths:
      - 'home/**'
      - .github/workflows/home.yml

jobs:
  e2e:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Run Cypress tests
        uses: cypress-io/github-action@v4
        with:
          working-directory: home
          build: npm run build
          start: npm start
          record: true
          wait-on: 'http://localhost:3000'
        env: 
          BLOG_URL: ${{ env.BLOG_URL }}
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN}}
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
  unit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install NPM dependencies
        uses: bahmutov/npm-install@v1
        with:
          working-directory: home
        env:
          CYPRESS_INSTALL_BINARY: 0

      - name: Run Jest tests
        run: npm run test
        working-directory: home